version: "3.9"

services:
  buddy-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    command: >
      sh -c "npm install && react-native start"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
  buddy-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: >
      sh -c "npm install && npm run start"
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server